# Generated by Django 3.0.5 on 2020-05-05 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200505_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='commentCount',
            new_name='comment_count',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='nameFilm',
            new_name='name_film',
        ),
    ]
