# Generated by Django 3.0.5 on 2020-04-30 15:45

import django.core.validators
from django.db import migrations, models
import django_enumfield.db.fields
import film.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('producerYear', models.PositiveIntegerField(help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2020)])),
                ('type', django_enumfield.db.fields.EnumField(enum=film.models.FilmType)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('detailPicture', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('reviewPoint', models.FloatField(blank=True, default=0, null=True)),
                ('reviewCount', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
