# Generated by Django 3.0.5 on 2020-05-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
