# Generated by Django 3.0.5 on 2020-05-01 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_film_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='type',
        ),
    ]
