# Generated by Django 3.0.5 on 2020-05-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_remove_film_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
