# Generated by Django 3.0.5 on 2020-05-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_film_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='detailPicture',
            field=models.ImageField(blank=True, null=True, upload_to='films/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='films/'),
        ),
    ]
