# Generated by Django 3.0.5 on 2020-05-03 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_auto_20200501_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='producerYear',
            field=models.PositiveIntegerField(help_text='Use the following format: <YYYY>', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2020)]),
        ),
    ]
