# Generated by Django 3.0.5 on 2020-05-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0007_auto_20200503_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='reviewCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
