# Generated by Django 3.0.5 on 2020-05-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0008_auto_20200503_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='detailPicture',
            new_name='detail_picture',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='producerYear',
            new_name='producer_year',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='reviewCount',
            new_name='review_count',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='reviewPoint',
            new_name='review_point',
        ),
    ]
